name: DevSoutinho
repository: https://github.com/devsoutinho/flutter-labs

# Where are the packages being required in this project?
packages:
  - libs/**
  - shells/**

command:
  bootstrap:
    usePubspecOverrides: true
  version:
      updateGitTagRefs: true

# What are the handfull scripts that you need in this monorepo?
scripts:
  hello: echo 'Hello World'

  ## CI Scripts
  lint:
    exec: dart analyze .
    description: Lint the Dart/Flutter codebase
  test:
    run: melos run test:selective_unit_test --no-select
    description: Run all Flutter tests in this project.
  ## Web Scripts
  build_shell_webportal: "cd ./shells/app.mariosouto.com && flutter build web --web-renderer html"
  deploy_web: "cd ./shells/app.mariosouto.com && npx vercel ./build/web --confirm --token=$VERCEL_TOKEN"
  deploy_web_prod: "cd ./shells/app.mariosouto.com && npx vercel ./build/web --confirm --token=$VERCEL_TOKEN --prod"
  preview_web: "cd ./scripts && node ./pullRequestPreview.js --experimental-fetch"
  ## Support
  test:selective_unit_test:
    run: melos exec --dir-exists="test" --fail-fast -- flutter test --no-pub --coverage
    description: Run Flutter tests for a specific package in this project.
    select-package:
      flutter: true
      dir-exists: test
