on:
  push:
  schedule:
    - cron: "0 * * * *"

env: 
  GH_STARS_TOKEN: ${{ secrets.GH_STARS_TOKEN }}

jobs:
  external_info:
    runs-on: ubuntu-latest
    name: "[Sync] DevSoutinho Youtube Vídeos"

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Call Script
      run: |
        git config --global user.email "13791385+omariosouto@users.noreply.github.com"
        git config --global user.name "Mario Souto - Bot"
        node -v
        ls -la
        yarn install
        yarn api start:ci
        sleep 5
        curl --request POST --header 'content-type: application/json' --url 'http://localhost:4000/api/graphql' --data '{"query":"mutation { syncYouTubeVideos { youtubeVideos { title } } }"}'
        git add .
        git commit -m "[sync] devSoutinho Youtube Vídeos" || echo "Up to date with main"
        git push origin HEAD
        echo "END: Youtube"
        echo "START: GH_Sync"
        curl --request POST --header 'content-type: application/json' --url 'http://localhost:4000/api/graphql' --data '{"query":"mutation SyncGitHubContributions { syncGitHubContributions { newContributions { title } } }"}'
        echo "END: GH_Sync"
