on:
  push:
  schedule:
    - cron: "0 * * * *"

jobs:
  external_info:
    runs-on: ubuntu-latest
    name: "[Sync] DevSoutinho Youtube Vídeos"

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Call Script
      run: |
        node -v
        ls -la
        yarn install
        yarn api start:ci
        curl --request POST --header 'content-type: application/json' --url 'http://localhost:4000/api/graphql' --data '{"query":"query { __typename }"}'
        echo "Im running!"
