on:
  push:
  schedule:
    - cron: "0 * * * *"

jobs:
  external_info:
    runs-on: ubuntu-latest
    name: "[Sync] DevSoutinho Youtube Vídeos"

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Call Script
      run: |
        node -v
        echo "Im running!"
